# Generated by Django 4.2.4 on 2023-11-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('mot_de_passe', models.CharField(max_length=50, verbose_name='Mot de passe')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('adresse', models.CharField(max_length=150, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('type_chambre', models.CharField(max_length=10)),
               
            ],
        ),
    ]
