# Generated by Django 4.2.4 on 2023-11-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0003_reservation_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='connexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('mot_de_passe', models.CharField(max_length=50, verbose_name='Mot de passe')),
            ],
        ),
    ]
