# Generated by Django 4.2.4 on 2023-11-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0004_connexion'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('message', models.CharField(max_length=2000, verbose_name='message')),
            ],
        ),
    ]
